name: Build

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run build --if-present
        env:
        
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}



          apiToken: L8ejzU1KbWspHLp6JIR1L5ZXy2Nh3uX1Gq2xXf-c
          secrets: |
            FAUNA_DB_KEY
          FAUNA_DB_KEY: fnAEVrP_-SACTG23SNcQEeolY5spCGGfyTk9E2XA
    
